language: go

addons:
  postgresql: "9.3"

services:
  - postgresql

go:
  - 1.4

before_install:
  - mkdir -p $HOME/gopath/bin
  - go install -a -race std
  - go get github.com/tools/godep
  - export PATH=$HOME/gopath/bin:$PATH
  - make bootstrap

before_script:
  - echo 'America/Los_Angeles' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

script:
  - godep go test -race ./...
