# Enable container based Travis stack
sudo: false

language: go

addons:
  postgresql: "9.3"

services:
  - postgresql

go:
  - 1.4

before_install:
  - mkdir -p $HOME/gopath/bin
  - L=$HOME/gopath/bin/hk && curl -sL -A "`uname -sp`" https://hk.heroku.com/hk.gz | zcat >$L && chmod +x $L
  - hk version
  - go install -a -race std
  - go get github.com/tools/godep
  - export PATH=$HOME/gopath/bin:$PATH
  - make bootstrap

before_script:
  - export TZ=America/Los_Angeles

script:
  - cd empire && godep go test -race ./...
