#!/bin/bash

phase=$1
target=$2

case "$target" in
  all)
    case "$phase" in
      deps)
        echo "../packages"
        echo "../build/emp"
        echo "deps"
        ;;
      exec) cat ../packages | xargs go test -race ;;
    esac ;;

  deps)
    case "$phase" in
      exec) ./deps ;;
    esac ;;

  *) >&2 echo "No rule for target \"$target\"" && exit 1 ;;
esac
