language: go

matrix:
  fast_finish: true

env:
  - CASS=1.2.19
  - CASS=2.0.11
  - CASS=2.1.2

go:
  - 1.2
  - 1.3
  - 1.4

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y libjna-java python-pip
  - sudo pip install cql PyYAML six
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - git clone https://github.com/pcmanus/ccm.git
  - pushd ccm
  - sudo ./setup.py install
  - popd
  - go get .

script:
  - set -e
  - go test -v -tags unit
  - bash -x integration.sh $CASS
  - go vet .

notifications:
  - email: false
