// Package events containers types representing GitHub webhook payloads. This
// package is autogenerated from https://github.com/github/developer.github.com/tree/master/lib/webhooks
package events

//go:generate ./generate
